-- --------------------------------------------------------

--
-- Structure de la table article
--


CREATE TABLE  article (
  codeArticle number(12) NOT NULL,
  libelleArticle VARCHAR2(200) NOT NULL,
  CONSTRAINT pk_article PRIMARY KEY (codeArticle)
);

-- --------------------------------------------------------

--
-- Structure de la table chapitre
--


CREATE TABLE  chapitre (
  codeChapitre number(12) NOT NULL,
  libelleChapitre VARCHAR2(200) NOT NULL,
  CONSTRAINT pk_chapitre PRIMARY KEY (codeChapitre)
);

-- --------------------------------------------------------
--
-- Structure de la table entitefinanciereprogramme
--


CREATE TABLE  entitefinanciereprogramme (
  EntiteFinanciereProgramme VARCHAR2(200) NOT NULL,
  NomenclatureComptable VARCHAR2(5) NOT NULL,
  CONSTRAINT pk_entite PRIMARY KEY (EntiteFinanciereProgramme)
); 

-- --------------------------------------------------------

--
-- Structure de la table presentationcroisee
--


CREATE TABLE  presentationcroisee (
  codePresentationCroisee number(12) NOT NULL,
  libellePresentationCroisee VARCHAR2(200) NOT NULL,
  CONSTRAINT pk_codePresentationCroisee PRIMARY KEY (codePresentationCroisee)
); 


-- --------------------------------------------------------

--
-- Structure de la table compte_admin_table
--


CREATE TABLE  compte_adm_tls (
  id number(12) GENERATED BY DEFAULT ON NULL AS IDENTITY NOT NULL ,
  ORDRE_REEL VARCHAR2(10) NOT NULL,
  DEPENSES_RECETTES VARCHAR2(10) NOT NULL,
  INVESTISSEMENT_FONCTIONNEMENT VARCHAR2(20) NOT NULL,
  CodeChapitre number(12) NOT NULL,
  CodeArticle number(12) NOT NULL,
  CodePresentationCroisee number(12) NOT NULL,
  EntiteFinanciereProgramme  VARCHAR2(200) NOT NULL,
  MontantRealise FLOAT NOT NULL,
  CONSTRAINT pk_compte_admin_table PRIMARY KEY (id),
  CONSTRAINT fk_codeArticle FOREIGN KEY (CodeArticle) REFERENCES article (codeArticle),
  CONSTRAINT fk_codeChapitre FOREIGN KEY (CodeChapitre) REFERENCES chapitre (codeChapitre),
  CONSTRAINT fk_codePresetation FOREIGN KEY (CodePresentationCroisee) REFERENCES presentationcroisee (codePresentationCroisee),
  CONSTRAINT fk_entiteFinanciere FOREIGN KEY (EntiteFinanciereProgramme ) REFERENCES entitefinanciereprogramme(EntiteFinanciereProgramme)
); 

-- --------------------------------------------------------
INSERT INTO ARTICLE(codeArticle, libelleArticle)
SELECT DISTINCT codeArticle, libelleArticle FROM compte_adm_tls;


INSERT INTO CHAPITRE(codeChapitre, libelleChapitre)
SELECT DISTINCT codeChapitre, libelleChapitre FROM compte_adm_tls;


INSERT INTO PRESENTATIONCROISEE(codePresentationCroisee, libellePresentationCroisee)
SELECT DISTINCT codePresentationCroisee, libellePresentationCroisee FROM compte_adm_tls;


INSERT INTO ENTITEFINANCIEREPROGRAMME(entiteFinanciereProgramme, nomenclatureComptable)
SELECT DISTINCT entiteFinanciereProgramme, nomenclatureComptable FROM compte_adm_tls;


INSERT INTO COMPTE_ADMIN_TABLE(Ordre_Reel,Depenses_Recettes,Investissement_Fonctionnement,codeChapitre,codeArticle,codePresentationCroisee,entiteFinanciereProgramme,montantRealise)
SELECT DISTINCT Ordre_Reel,Depenses_Recettes,Investissement_Fonctionnement,codeChapitre,codeArticle,codePresentationCroisee,entiteFinanciereProgramme,montantRealise FROM compte_adm_tls;

COMMIT;